### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by al8n** [al8n/rarena#4]
# Tier 1
- [x] `rarena-allocator`: Lock-free in-memory and on-disck ARENA implementation.
- [ ] `rarena-skiplist`: A lock-free skiplist implementation based on ARENA.
- [ ] `rarena-linkedlist`: Lock-free linked list implmentations based on ARENA.
